[package]
name = "lance-graph"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Lance Devs <dev@lancedb.com>"]
repository = "https://github.com/lancedb/lance-graph"
readme = "README.md"
description = "Graph query engine for Lance datasets with Cypher support"
keywords = ["lance", "graph", "cypher", "query", "datafusion"]
categories = ["database", "data-structures", "science"]

[dependencies]
arrow = { version = "55.2", features = ["prettyprint"] }
arrow-array = "55.2"
arrow-schema = "55.2"
datafusion = { version = "49.0.2", default-features = false, features = [
    "nested_expressions",
    "regex_expressions",
    "unicode_expressions",
    "crypto_expressions",
    "encoding_expressions",
    "datetime_expressions",
    "string_expressions",
] }
datafusion-common = "49.0.2"
datafusion-expr = "49.0.2"
datafusion-sql = "49.0.2"
lance-core = "0.37.0"
nom = "7.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
snafu = "0.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["async", "async_tokio", "html_reports"] }
futures = "0.3"
lance = "0.37.0"
tempfile = "3"
tokio = { version = "1.37", features = ["macros", "rt-multi-thread"] }

[[bench]]
name = "graph_execution"
harness = false
