[package]
name = "lance-graph-python"
version = "0.1.0"
edition = "2021"
authors = ["Lance Devs <dev@lancedb.com>"]
publish = false

[lib]
name = "_internal"
crate-type = ["cdylib"]

[dependencies]
arrow = { version = "55.2", features = ["pyarrow"] }
arrow-array = "55.2"
arrow-schema = "55.2"
arrow-ipc = "55.2"
futures = "0.3"
lance-graph = { path = "../rust/lance-graph" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
pyo3 = { version = "0.24.1", features = ["extension-module", "abi3-py39", "py-clone"] }
tokio = { version = "1.37", features = ["rt-multi-thread", "macros"] }
