name: Style Check
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - rust/**
      - .github/workflows/style.yml
      - rust/lance-graph/Cargo.toml
      - rust/lance-graph/Cargo.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C debuginfo=1"

jobs:
  format:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --manifest-path rust/lance-graph/Cargo.toml -- --check

  clippy:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust/lance-graph
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler
      - name: Clippy
        run: cargo clippy --manifest-path rust/lance-graph/Cargo.toml --all-targets -- -D warnings

  typos:
    name: Spell Check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@v1.26.0